version: '3.5'

networks:
    dcc:

services:
    procesosmg:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: procesosmg
        environment:
            - PORT=80
        ports:
            - "80:80"

